### PR TITLE
Changed the Menu of before 

### PR DESCRIPTION
**Pull request by Jannik143**
The mistakes of the menu got fixed so check if i missed something if possible ^^

### CODE REVIEW

**Comment by alextopher0** [comment]
Woah that's a lot of commits!

**Comment by Jannik143** [comment]
Yeah but to be fair I m new to github and don't know how it works :P 
I bet you could remove every deleted file from this somehow

**Comment by alextopher0** [comment]
I'm gonna checkout you're project and look at it hold tight

**Comment by Jannik143** [comment]
Okay thanks :)

**Comment by alextopher0** [comment]
Looks like your fork is behind master, lets get that caught up first then talk about where to put your classes.

In https://docs.google.com/document/d/1p5i64NT7B5y-CNH9MyeQT5jwRByZ2o8yJnSnykOSJNQ/edit# there is a section about updating your fork

**Comment by atsharrock** [comment]
Can i just mention some of your commented code is written in both English and German.

Please forgive me if this is rude but could i suggest the comments to be written in English? Just so the native only speakers among us don't have to translate each time.

I'm ok with translating i just thought it may save some people time :-)

**Comment by DevOrc** [comment]
We might want to squash/rebase this when this gets merged so that it shrinks to one commit

**Comment by Jannik143** [comment]
Yeah that was my bad the commented code comes from myself and someone who helped me with the menu and we are both german thats why some of the comments are german as well ^^

**Comment by RedRoyalDog** [comment]
Would love to merge this --- Tag me when all the German is cleaned up to English. :)

**Comment by alextopher0** [comment]
I can't see the merge conflict I'm looking into more

**Pull request merged**
