### PR TITLE
Code restructure, details in comment.

### PR DESCRIPTION
**Pull request by lemikistu**
Had to submit new pr with new commit message and better title.Added Entity Class with all fields we defined in UML , created Ant,Wasp and Spider classes which inherited from entity class, created QueenAnt and WorkerAnt class which inherited from Ant class. Removed game and player.java as those didn't had any use. Removed getters  and setters as these were not needed in inheritance environment.

### CODE REVIEW

**Comment by DoroGi** [comment]
I wouldn't delete the game tick logic.
As most of the code it's only a stub, but a stub that we will surely need in the future… If we start deleting and reintroducing the stubs we will never come to an end.
Even your classes are not used in the main… Following the "as those didn't had any use" criteria most of our code, this commits included would be deleted.

**Comment by DoroGi** [comment]
As a separate observation, I would probably squash a bit the commits.
This is supposed to be a project to show newcomers the best practices, so we should follow them also with our commit history!

**Comment by lemikistu** [comment]
Yeah but you can't submit random code like tick  when it has no use right now. It makes development harder. Also I didn't wanted to make bunch of commits for fundamental work as it would make submission harder to assist.

**Comment by lemikistu** [comment]
In the future when things settle I would surely do it but for now I am trying to have ground work for new people to contribute to.

**Pull request merged**
