### PR TITLE
package names were wrong in each file

### PR DESCRIPTION
**Pull request by ThaGazer**
When I cloned the current master branch I couldn't compile. I believe it was be cause the package tag in each file was wrong. So I changed them if you want to update. This can also be fixed if the source root is defined differently but I don't expect everyone about this. It might also depend on which IDE and compiler flags everyone is using.

### CODE REVIEW

**Comment by RedRoyalDog** [comment]
@ThaGazer Can you set a reviewer to verify this?

**Comment by ThaGazer** [comment]
How does one set a reviewer

**Comment by alextopher0** [comment]
I agree we should have cleaner package names but they all are legal at the moment. There is a main/java directory under src. I'd be cool if you updated them to `com.github.warofants.wwa` in the meantime

**Comment by alextopher0** [comment]
Hey people, I figured it out. We we're missing a line in pom.xml that would have prevented this issue a new PR is coming into existence (you're still welcome to update the package names afterwards)

**Comment by RedRoyalDog** [comment]
It sounds like #18  fixes this.

**Pull request closed without merging**
