### PR TITLE
undo my commit on main branch

### PR DESCRIPTION
**Pull request by root-ansh**
So here is what that happened:
- I forked this repo a few days ago, there was no `development` branch then, only `master`
- I checked the code, found a minor bug, corrected it , committed it  and pushed the change to my repo.  
- then i submitted a PR on main repo.
- Then i received a response that my PR cannot be merged on the `main` and i have to push my changes in the develop branch, if they require such. ( I mean, since it got created late, i guess it might have other code that would lead to collision with the code that i added)  

So here is what i have understood that i need to do: revert my changes on the main branch, pull changes from the original repo, pull those changes locally and then add my changes if needed.  
So here is what i am doing:
- i tried to revert my changes. i used `git revert <my commit hash>` , `git push -u origin master` to do so, but it has created another commit with title `removed bad commit`
- I created a branch called development in my online fork using github's  [gui](https://user-images.githubusercontent.com/31290636/63723584-70c0f980-c873-11e9-9c70-9b5e1b9f7d38.png).  (I also added a remote upstream using `git remote add upstream original_repo_link.git` and did a `git fetch upstream` ).
- Its asking for a pull request, so here it is.

### CODE REVIEW

**Comment by root-ansh** [comment]
@Veradux need your thoughts on this. am i on the right track?

**Comment by root-ansh** [comment]
>Then i received a response that my PR cannot be merged on the main and i have to push my changes in the develop branch, if they require such. ( I mean, since it got created late, i guess it might have other code that would lead to collision with the code that i added)  

That's what have happened! from what i can see in my intellij code, as soon as i switch branches using `git checkout development` or  `git checkout master`,  the code completely changes and develop branch no longer requires my changes.  

So reviewers, i guess i need you guys to review this PR so that  `master` branch of  <B>my fork( and local clone) </B>  remains in sync with the `master` branch of <b><i> original repo</i></b>

**Comment by Plat251** [comment]
To change a Pull Request target branch, you can just hit Edit to the right of Pull Request name and choose a new branch to push into.

To make sure you're working on an up-to-date version in the future:
https://help.github.com/en/articles/syncing-a-fork

To fix problems related to you not working on an up-to-date-version:
https://help.github.com/en/articles/about-git-rebase

**Comment by root-ansh** [comment]
i figured out!  
just had to change bases using this ui:  
[ui](https://user-images.githubusercontent.com/31290636/63806288-e3e07380-c938-11e9-97a3-6f30dbe16b64.png)  

Now next time i create a pr(by making changes on development branch), it will show an addition of 2 commits which , as Plat said, cancels each other out and doesn't add anything significant to project.  
Wonder what would happen once some code is pushed to master branch.  

Closing this PR, Thankyou @Plat251  and @anthonyLuttrell  again for your support!😄

**Pull request closed without merging**
