### PR TITLE
Access Text Document with String Reader

### PR DESCRIPTION
**Pull request by BramLobbens**
I've created AboutUsAssets from which we can read text from an assets folder in order to keep the code separate from any external documentation.

### CODE REVIEW

**Comment by BramLobbens** [comment]
Hello Raveesh. You are most likely right. Unfortunately I haven't been exposed to many Java 8+ features like streams, much so I went with what I know.
I understand skill and knowledge levels will vary within this project. I'll discuss within the team.
It's definitely a good opportunity to learn however, and I will have a look to update to using streams.

**Comment by Plat251** [comment]
Hello, disregard anything Alextopher0 said about package names, as we've since moved on to a different package naming convention. Please make sure that any of the new files have appropriate package name as their very first line. 
`com.worldwarofants.game.io` if they're in the \io folder.

**Comment by Veradux** [comment]
What are you planning on having in these asset files, to deem this necessary?

**Comment by RedRoyalDog** [comment]
@Plat251 @Veradux Please review this merge request, and let me know your findings.

@BramLobbens Please resolve conflicts.

**Comment by Plat251** [comment]
It looks outdated, abandoned and solves a very
The code within isn't very flexible or reusable.
Unless @BramLobbens is willing to outline a purpose for this and overhaul it, it is not useful.

**Comment by BramLobbens** [comment]
So this was made in the beginning stages when the--now abandoned--groups were created in response to a task on Trello. However it is probably safe to say that it's indeed no longer applicable to the current code base. I should probably close this then?

**Comment by Plat251** [comment]
@BramLobbens 
That would be an appropriate course of action.

**Comment by BramLobbens** [comment]
Ok, closing.

**Pull request closed without merging**
