### PR TITLE
changed indent of Entity class to 4 spaces instead of 3

### PR DESCRIPTION
**Pull request by root-ansh**
Used IntelliJ's auto indent feature to update  spaces.

### CODE REVIEW

**Comment by root-ansh** [comment]
@Veradux  Hi. So i need help understanding your request. I currently have the  original repo forked from 5-6 days before and without any latest changes. My repo rather shows its ahead of original repo by 1  commit:  
image  

I know i can just close this pr, nuke my fork re fork and then make a pr again, but i guess htat's not the right way. Can you tell me how what steps should i take next in this situation?

**Comment by Veradux** [comment]
> @Veradux Hi. So i need help understanding your request. I currently have the original repo forked from 5-6 days before and without any latest changes. My repo rather shows its ahead of original repo by 1 commit:
> image
> 
> I know i can just close this pr, nuke my fork re fork and then make a pr again, but i guess htat's not the right way. Can you tell me how what steps should i take next in this situation?

First of all, it would be helpful to mirror all of the branches in the main repository. Currently there are branches master, and development. 
* master is for releases.
* development is for combining everyone's work and making sure it fits together and works properly, before putting it in master.

You are missing the development branch. A simple way to do that is:
* Create a new branch in your repository, called development. 
* Make a PR from the main repo's development, to your own fork's development.
* Approve that PR.

Then, when you write code, it should be submitted to your own development branch. After that, when you think it's ready, you make a PR from your development, to the main repo's development.

**Comment by blackk100** [comment]
#66

**Comment by root-ansh** [comment]
closing since master branch is not taking a pr and development branch no longer requires these changes

**Pull request closed without merging**
