### PR TITLE
Created New Classes for ant types based on species team requirement sheet

### PR DESCRIPTION
**Pull request by lemikistu**

### CODE REVIEW

**Comment by Plat251** [comment]
We discussed making "Ant" a composite class made up of traits and species. Hardcoding every species as a separate class is not the way to go.

**Comment by lemikistu** [comment]
Okay we can try composition then. Until then we can keep this pr open.

**Comment by alexdqmf** [comment]
I say we close it. Lemikistu even deleted his own fork... and this one doesn't apply anyway.

**Comment by Plat251** [comment]
Closing due to this being outdated and unmaintained.

**Pull request closed without merging**
