### PR TITLE
Remove I prefix from Interface names

### PR DESCRIPTION
**Pull request by nylanderdev**

### CODE REVIEW

**Comment by alexdqmf** [comment]
# [Codecov](https://codecov.io/gh/warofants/wwa/pull/145?src=pr&el=h1) Report
> Merging [#145](https://codecov.io/gh/warofants/wwa/pull/145?src=pr&el=desc) into [development](https://codecov.io/gh/warofants/wwa/commit/c9e208dc4fe55fb9fa1ce9d6b6c16df9acdbb649&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/warofants/wwa/pull/145?src=pr&el=tree)

```diff
@@              Coverage Diff               @@
##             development     #145   +/-   ##
==============================================
  Coverage          13.38%   13.38%           
  Complexity             8        8           
==============================================
  Files                 19       19           
  Lines                157      157           
  Branches               3        3           
==============================================
  Hits                  21       21           
  Misses               136      136           
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/warofants/wwa/pull/145?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/warofants/wwa/pull/145?src=pr&el=footer). Last update [c9e208d...3cde54a](https://codecov.io/gh/warofants/wwa/pull/145?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by Veradux** [comment]
What is the purpose of this? What do we gain from removing the prefixes?

**Comment by nylanderdev** [comment]
It's important to establish proper conventions early on in development. The "I" prefix is somewhat frowned upon, and for good reason (see quote).

"I prefer to leave interfaces unadorned. The preceding I, so common in today’s legacy wads, is a distraction at best and too much information at worst. I don’t want my users knowing that I’m handing them an interface." - Robert "Uncle Bob" Martin, Clean Code

**Comment by Veradux** [comment]
> It's important to establish proper conventions early on in development. The "I" prefix is somewhat frowned upon, and for good reason (see quote).
> 
> "I prefer to leave interfaces unadorned. The preceding I, so common in today’s legacy wads, is a distraction at best and too much information at worst. I don’t want my users knowing that I’m handing them an interface." - Robert "Uncle Bob" Martin, Clean Code

The reason why I added the prefix was because a lot of new people had interest in the project, and I wanted to make it more obvious what each type was.

Thanks for the quote. But this doesn't sound like a full explanation. Why would you want to hide the fact that you're handing the users an interface? How can this information become too much, why is it harmful? I'm very interested in learning more about this.

**Pull request closed without merging**
