### PR TITLE
Feature/base architecture

### PR DESCRIPTION
**Pull request by Veradux**
### Today is a good day to learn about a couple of the **SOLID** principles! 

If any of the following sounds like an alien language to you, then don't worry. In that case it will not matter to you that much. I am hoping that the team mentors can pick up on what I am presenting, and that they can then translate anything that is necessary to know to the team members.

## Single Responsibility Principle
This architecture's goal is to offer a clean way to achieve separation of concerns. Both between classes in the program, and between teams and team members.  Each class aims to have _responsibility_ for only one single thing.

* Teams will have their completely separate playground, where they can develop on their own, without having to worry about outside factors or other teams too much.

* As long as each member has a well thought out task, they will not get in the way of other people, and other people should not get in the member's way.

## Open / Closed Principle
Or in other words, _open_ for extension, but _closed_ for modification. 

* The base classes offered here are made with the purpose to be extended and reused, with the purpose to only constrict you in a way that is helpful for the development.

* They are also made so that you rarely have to worry about them. Their interface is not cluttered, and the things that they contain has restricted access.

## Dependency Inversion Principle
The base classes are made to be put together without many "self constructed" dependencies. That means that the dependencies come from outside. Usually that creates a few complications as well. Most of the time projects deal with those complications with external frameworks. Those will not be needed here! 

There are two other principles, but I decided to omit them, to avoid giving people too many headaches. Here is a resource which explains them in detail. https://itnext.io/solid-principles-explanation-and-examples-715b975dcad4

## MVC
This architecture follows the MVC pattern. There is no reason to be frightened, if that is new to you! It's not as big of a deal as it sounds. It is also a good opportunity to get familiar with it. MVC just means that things are split up into Models, Views, and Controllers. There are also influences from some other patterns, but they are not as important.

* A very concise explanation of MVC: https://www.youtube.com/watch?v=DUg2SWWK18I
* An example of how MVC is done: https://www.youtube.com/watch?v=dTVVa2gfht8

## Documentation
The architecture is heavily documented. And it will continue to be documented in the following weeks. 

* There are explanations of what each thing is right inside of the code, so you can see what each thing is supposed to be, and how it is used, while you are in your IDE and working on the game! 

* There even is an example of how to use the architecture! It is written in a bit of a hurry, because as one smart person said, "if your first built isn't embarrassing, then you have taken too long to publish it". ;) There are still things to be done, and ways to improve things. But there will be a team formed with the purpose of maintaining it and adjusting it to fit people's future needs.

The way I would highly recommend to read it, before it is approved, is to open a terminal where you want to save the project, and to clone it like so:
* git clone https://github.com/Veradux/wwa.git
* cd wwa
* git checkout -b feature/base_architecture

Or for the lazy, you can do all of that with one command, just copy and paste this in your terminal: 
* git clone https://github.com/Veradux/wwa.git && cd wwa && git checkout -b feature/base_architecture

* For some IDEs you can enable the documentation to show up while hovering over the methods and classes. That is the best way to read it in my opinion. 
* For Eclipse, it should be automatically enabled, if I recall correctly. 
* For Intellij, you can enable it by going through File > Settings > Editor > General > Other > Show quick documentation on mouse move. Or just search for it in the search bar. 
* This is how it looks, when hovering over something!

docs

## Overview
* The green components are part of the MVC. 
* The yellow ones are part of the Console version of the game, which is how things will start. 

Untitled Diagram

* There are ways that this architecture could be made to support other visualizations, like 2D. Simply said, that will have to be done by "replacing" the View and Console components. That would require a bit more work, but it is not out of the question yet.

### CODE REVIEW

**Comment by suppergerrie2** [comment]
I may misunderstand the system so if I do please tell me.

I cant see how I would do something like that takes multiple "turns/ticks' like for example scouting, where you send an ant to scout and then x turns later it comes back, and in the meantime you can start other tasks like more scouting, combat, expanding the nest. There doesn't seem to be something that "ticks". Do I see this correctly?

**Comment by Veradux** [comment]
> I may misunderstand the system so if I do please tell me.
> 
> I cant see how I would do something like that takes multiple "turns/ticks' like for example scouting, where you send an ant to scout and then x turns later it comes back, and in the meantime you can start other tasks like more scouting, combat, expanding the nest. There doesn't seem to be something that "ticks". Do I see this correctly?

You are correct, there is no such thing implemented. Thank you for the good question! The main thing that this pull request is concerned with, is separating code by what it does, and putting it together in its own place, away from other kinds of code.

What it is not concerned with, is how the game play elements will be designed. You should be able to fit almost anything into this architecture. It doesn't even have to be a game. In fact, a lot of back end servers and stuff are designed like this.

What I'm trying to say is, you can easily code that tick feature and put it into this. It doesn't exist, but it can be implemented.

The reason why I avoided adding any specific game play code is because I wanted each team to be responsible for their own features, and the way they work. As long as everyone else is okay with that approach of course.

**Comment by suppergerrie2** [comment]
Ah okay, that makes sense. 
I had one more question, I was looking at how the controller and such work, and saw that each controller has its own command handler, and thus its own commands. I may be incorrect but wouldnt this mean that you need some sort of "startScouting" "startCombat" command in the main controller so you can switch the the scouting and combat controller?

**Comment by Veradux** [comment]
> Wouldnt this mean that you need some sort of "startScouting" "startCombat" command in the main controller so you can switch the the scouting and combat controller?

The switching will be tied to a command, yes. It has to be triggered somehow! But it doesn't have to be a command that only switches and does nothing else. It is up to the design and the flow of the game. 

The way you can switch between those things, which are called Modules, is pretty simple. You can do it in any controller, and you can go to any other controller too. It is done by calling ``` navigateTo(ModuleName) ``` inside any controller's methods.

After this method call, any following command will now be processed by that other module.

**Comment by suppergerrie2** [comment]
> It is done by calling navigateTo(ModuleName) inside any method in the controllers.
Yeah I saw that, but can you for example do:
`scout` -> `navigateTo(SCOUT)` -> then scout will further handle the scout command?

**Comment by Veradux** [comment]
> further handle the scout command
I'm not sure how that can be done the way things are right now, and what it can be used for. But I think I know how I can make it happen. 

What I can do is add a starting command to every module. And whenever you switch to it, that command gets executed with the arguments passed in.

Do you think that will be enough, for what you have in mind?

**Comment by suppergerrie2** [comment]
I think that should be enough at the moment.
I'm currently trying to implement some stuff and am missing for example antgroups, but if I understood your earlier comment that is out of scope for this PR.

**Pull request merged**
