### PR TITLE
Wrote a large base code to propel the project into the next stage

### PR DESCRIPTION
**Pull request by alextopher0**
For the longest time we've been trying to work without any sort of guidance. Hopefully we can change that. With this code being released we're going to be splitting into a ton of teams and start cracking at finishing this project.

The additions to the code base are intense but they are just the beginning. Much of the code is empty with simple calls to functions waiting for logic to be added. I tried my hardest to connect all the blocks in the diagram, and I hope I got enough of them added that there isn't much room for stepping on each others feet.

The package structure has been built on. Now there is a constants folder to store YAML files and a yaml decoder. 

The logic I did add is a World object to handle the 2d over world much of the game takes place. I'd say it's _near_ finished, only minor changes maybe added.

### CODE REVIEW

**Comment by Plat251** [comment]
Well, where do I even start.
I guess there's an advantage to gargantuan pull requests like this - noone can criticize them if they can't get to the end of it.
But we're not here to give up like that, so let's try breaking it down.

- The name isn't good.
It sure describes the code within - it's truly large, and just as not good at describing itself as the pull request. It also documents as much as the code - wow, there's a lot of stuff. That's cool. What does it do? How does it do it? Is it going to hurt?
Also, it doesn't fit the "If you add this to your repository, it will \<Wrote a large base code\>". 
- The commits aren't good.
Commits are supposed to be logical, readable, and at least somewhat atomic. Four commits for 1.2k lines of code added, across 44 files? That's neither of those things. How is this meant to be reviewed, tested, who knows what other stuff it will end up breaking?
- The pull request isn't very good either.
Do you know how many PRs were already dealing with features you implemented here, and how many of them are now a headache because this one is conflicting with them? I don't know either! 

There are undeniable and demonstrable advantages to writing small, logical commits. There are also benefits to using different branches for different features, so that you don't have to make PRs that are just dumps of everything written so far.

However, since the main repository is small at the moment, we might end up getting away with merging this. I'll wait for others to speak their mind on this.
Please don't propose such unorganized and messy changes in the future.

**Comment by realDragonium** [comment]
Alright, so a couple design question. Im not trying to tell you that you're wrong. Im just wondering why you did it like this?

 - Why did you decided to add an api? So every class/object could talk to the world? If so, doesnt this make the code more thight coupled? 

- And what if we wanted to add extra worlds or maybe even with special traits to a world, can we still use your api?

- Why are you making different classes for Ant and Wild? Wont this cause quite some duplicated code? Same goes for Human and AI classes

**Comment by JeffUTF8** [comment]
I'm going to have such a fun time porting this to C++.

**Comment by Veradux** [comment]
Yeah can you go into more detail what you are hoping to gain from adding that world API and the API requests? Don't they just end up calling methods of the World? What are your plans for those classes?

**Comment by Plat251** [comment]
If these changes have been manually incorporated, perhaps it is time to close this PR?

**Comment by RedRoyalDog** [comment]
@Plat251 Is this good to close?

Reasons)
1. Too large of a merge request without proper details.
2. Several features have already been implemented.
3. This MR can be cherry-picked into smaller MRs to be easier reviewed and merged

@Plat251 please verify.

**Comment by Plat251** [comment]
Yes, it has been made obsolete by #71, some of its features implemented manually.

**Pull request closed without merging**
